apiVersion: v1
kind: Service
metadata:
  name: jerney-backend
spec:
  type: {{ .Values.backend.service.type}}
  selector:
    app: jerney-backend
  ports:
    - port: {{ .Values.backend.service.port}}
      targetPort: {{ .Values.backend.service.port}}     