apiVersion: v1
kind: Service
metadata:
  name: jerney-frontend
spec:
  type: {{ .Values.frontend.service.type}}
  selector:
    app: jerney-frontend
  ports:
    {{- range .Values.frontend.service.ports}} 
    - port: {{.port}}
      targetPort: {{.targetPort}}
    {{-end}}     