apiVersion: v1
kind: Service
metadata:
  name: jerney-frontend
spec:
  type: {{ .Values.frontend.service.type}}
  selector:
    app: jerney-frontend
  ports:
    - port: {{ .Values.frontend.service.port}}
      targetPort: {{ .Values.frontend.service.port}}     