apiVersion: v1
kind: Secret
metadata:
  name: jerney-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.db.secretUser | quote }}
  DB_PASSWORD: {{ .Values.db.secretPassword | quote }}
  DB_NAME: {{ .Values.db.secretName | quote }}